name: Terraform CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  terraform:
    uses: mbologna/.github/.github/workflows/terraform-ci.yml@4df74894bb7396d6abbf3baf4bcdf8ec9b9bed39 # main
    with:
      working_dir: ./example
